
#############
# SERVICIO  
#############
apiVersion: v1
kind: Service
metadata:
  name: colors-service
  namespace: n1
  labels:
     app: color
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
     app: color