#############
# DEPLOYMENT  
#############
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: colors
  namespace: n1
spec:
  selector:   
    matchLabels:
      app: color
  replicas: 3
  template:  
    metadata:
      labels:
        app: color
    spec:
      containers:
      - name: coloread
        image: noloknolo/colors:v1
        ports:
        - containerPort: 8080

