apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: demogatyaml
spec: 
  selector:   
    matchLabels:
      app: gato 
  replicas: 2 
  template:   
    metadata:
      labels:
        app: gato 
    spec: 
      containers:
      - name: tomcat
        image: tomcat:11.0.0-M20
        ports:
        - containerPort: 80 #puerto por el que escucha el servidor (la imagen)